"""add player country

Revision ID: 25f1a66a71ae
Revises: 78271a110100
Create Date: 2026-09-06 16:39:08.471349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25f1a66a71ae'
down_revision: Union[str, Sequence[str], None] = '78271a110100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.create_index(op.f('ix_players_country'), 'players', ['country'], unique=False)
    op.drop_column('players', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_players_country'), table_name='players')
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.drop_column('players', 'country')
    # ### end Alembic commands ###
