"""add position to Players table model

Revision ID: 45d87296611c
Revises: 649689d25d1b
Create Date: 2026-09-08 05:48:58.559324

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45d87296611c"
down_revision: str | Sequence[str] | None = "649689d25d1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.execute("""
        UPDATE players
        SET position = CASE normalized_name
            WHEN 'janina leitzig' THEN 'goalkeeper'
            WHEN 'phallon tullis-joyce' THEN 'goalkeeper'
            WHEN 'andrea medina' THEN 'defender'
            WHEN 'anna sandberg' THEN 'defender'
            WHEN 'dominique janssen' THEN 'defender'
            WHEN 'hanna lundkvist' THEN 'defender'
            WHEN 'jayde riviere' THEN 'defender'
            WHEN 'jess simpson' THEN 'defender'
            WHEN 'lucy newell' THEN 'defender'
            WHEN 'maya le tissler' THEN 'defender'
            WHEN 'rebeca bernal' THEN 'defender'
            WHEN 'scarlett hill' THEN 'defender'
            WHEN 'ella toone' THEN 'midfielder'
            WHEN 'emma watson' THEN 'midfielder'
            WHEN 'hinata miyazawa' THEN 'midfielder'
            WHEN 'jess park' THEN 'midfielder'
            WHEN 'jessica anderson' THEN 'midfielder'
            WHEN 'julla ziglotti olme' THEN 'midfielder'
            WHEN 'maren griffiths' THEN 'midfielder'
            WHEN 'simi awujo' THEN 'midfielder'
            WHEN 'celin bizet' THEN 'forward'
            WHEN 'elisabeth terland' THEN 'forward'
            WHEN 'ellen wangerhelm' THEN 'forward'
            WHEN 'fridolina rolfö' THEN 'forward'
            WHEN 'layla drury' THEN 'forward'
            WHEN 'lea schüller' THEN 'forward'
            WHEN 'monica jusu bah' THEN 'forward'
        END
    """)
    op.alter_column(
        "players",
        "position",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    op.alter_column("players", "country", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_players_position"), "players", ["position"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_players_position"), table_name="players")
    op.alter_column("players", "country", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("players", "position")
    # ### end Alembic commands ###
