"""import csv

Revision ID: 649689d25d1b
Revises: 25f1a66a71ae
Create Date: 2026-09-06 17:22:41.920529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '649689d25d1b'
down_revision: Union[str, Sequence[str], None] = '25f1a66a71ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('players', sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('players', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('players', 'normalized_name')
    op.drop_column('players', 'display_name')
    # ### end Alembic commands ###
